# Generated by Django 2.2.2 on 2020-04-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200405_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='price',
            new_name='rent',
        ),
    ]
