# Generated by Django 2.2.2 on 2020-04-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=25, upload_to='blog_pics'),
            preserve_default=False,
        ),
    ]
