# Generated by Django 2.2.2 on 2020-04-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='house',
            field=models.CharField(choices=[('all', 'all'), ('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('sinle room', 'SINGLE ROOM')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='tenant',
            field=models.CharField(choices=[('boys', 'BOYS'), ('girls', 'GIRLS'), ('family', 'FAMILY'), ('single', 'BOYS/GIRLS'), ('all', 'ALL TYPE')], default='all', max_length=10),
        ),
    ]
