# Generated by Django 2.2.2 on 2020-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200413_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='blog_pics'),
        ),
    ]
