# Generated by Django 2.2.2 on 2020-04-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
