# Generated by Django 2.2.2 on 2020-05-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
